'use strict';
const SHAPES={I:[[0,0,0,0],[1,1,1,1],[0,0,0,0],[0,0,0,0]],J:[[1,0,0],[1,1,1],[0,0,0]],L:[[0,0,1],[1,1,1],[0,0,0]],O:[[1,1],[1,1]],S:[[0,1,1],[1,1,0],[0,0,0]],T:[[0,1,0],[1,1,1],[0,0,0]],Z:[[1,1,0],[0,1,1],[0,0,0]]};
const COLORS={I:'#55d9ef',J:'#5c89fa',L:'#ffa65c',O:'#f5d964',S:'#6de0ac',T:'#b68bfa',Z:'#fb718b'};
class Game{
 constructor(){this.reset()}
 reset(){this.board=Array.from({length:20},()=>Array(10).fill(null));this.queue=[];this.bag=[];this.score=0;this.lines=0;this.held=null;this.canHold=true;this.over=false;this.fill();this.spawn()}
 get level(){return 1+Math.floor(this.lines/10)}
 fill(){while(this.queue.length<5){if(!this.bag.length){this.bag=Object.keys(SHAPES);for(let i=6;i>0;i--){let j=Math.floor(Math.random()*(i+1));[this.bag[i],this.bag[j]]=[this.bag[j],this.bag[i]]}}this.queue.push(this.bag.pop())}}
 spawn(type){this.type=type||this.queue.shift();this.fill();this.matrix=SHAPES[this.type].map(r=>r.slice());this.x=Math.floor((10-this.matrix.length)/2);this.y=0;this.canHold=true;if(!this.valid())this.over=true}
 valid(m=this.matrix,x=this.x,y=this.y){return m.every((r,dy)=>r.every((v,dx)=>!v||(x+dx>=0&&x+dx<10&&y+dy<20&&(y+dy<0||!this.board[y+dy][x+dx]))))}
 move(dx,dy){if(this.over)return false;if(this.valid(this.matrix,this.x+dx,this.y+dy)){this.x+=dx;this.y+=dy;return true}return false}
 rotate(dir=1){if(this.over)return;const m=this.matrix[0].map((_,i)=>this.matrix.map(r=>r[i]).reverse());const rotated=dir===1?m:m.map(r=>r.slice().reverse()).reverse();for(const [dx,dy] of [[0,0],[-1,0],[1,0],[-2,0],[2,0],[0,-1],[-1,-1],[1,-1],[0,-2]])if(this.valid(rotated,this.x+dx,this.y+dy)){this.matrix=rotated;this.x+=dx;this.y+=dy;return true}return false}
 ghostY(){let y=this.y;while(this.valid(this.matrix,this.x,y+1))y++;return y}
 hold(){if(!this.canHold||this.over)return false;let old=this.type;if(this.held)this.spawn(this.held);else this.spawn();this.held=old;this.canHold=false;return true}
 lock(){if(this.over)return 0;let above=false;this.matrix.forEach((r,dy)=>r.forEach((v,dx)=>{if(v){if(this.y+dy<0)above=true;else this.board[this.y+dy][this.x+dx]=this.type}}));if(above){this.over=true;return 0}const remaining=this.board.filter(r=>r.some(v=>!v));const cleared=20-remaining.length;this.score+=[0,100,300,500,800][cleared]*this.level;this.lines+=cleared;this.board=[...Array.from({length:cleared},()=>Array(10).fill(null)),...remaining];this.spawn();return cleared}
 drop(){if(this.over)return 0;let y=this.ghostY();this.score+=(y-this.y)*2;this.y=y;return this.lock()}
}
if(typeof module!=='undefined')module.exports={Game,SHAPES};
if(typeof document!=='undefined'){
const $=id=>document.getElementById(id),game=new Game(),ctx=$('board').getContext('2d');let running=false,paused=false,last=0,fall=0,grounded=0,resets=0,best=0,sound=false,audio;
try{best=Number(localStorage.getItem('cp-tetris-best'))||0}catch{}
function tone(freq=400,duration=.07){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}}
function block(c,x,y,size,color,ghost=false){c.fillStyle=ghost?'#18303b':color;c.fillRect(x+1,y+1,size-2,size-2);c.strokeStyle=ghost?color:'#ffffff40';c.lineWidth=ghost?1:2;c.strokeRect(x+2,y+2,size-4,size-4);if(!ghost){c.fillStyle='#ffffff27';c.fillRect(x+3,y+3,size-6,3)}}
function preview(id,types){const c=$(id).getContext('2d');c.clearRect(0,0,120,c.canvas.height);types.forEach((type,i)=>{if(!type)return;let m=SHAPES[type],s=23,ox=(120-m.length*s)/2,oy=i*70+10;m.forEach((r,y)=>r.forEach((v,x)=>{if(v)block(c,ox+x*s,oy+y*s,s,COLORS[type])}))})}
function render(){ctx.clearRect(0,0,300,600);ctx.strokeStyle='#ffffff06';ctx.lineWidth=1;for(let x=0;x<=10;x++){ctx.beginPath();ctx.moveTo(x*30,0);ctx.lineTo(x*30,600);ctx.stroke()}for(let y=0;y<=20;y++){ctx.beginPath();ctx.moveTo(0,y*30);ctx.lineTo(300,y*30);ctx.stroke()}game.board.forEach((r,y)=>r.forEach((v,x)=>{if(v)block(ctx,x*30,y*30,30,COLORS[v])}));if(!game.over){const gy=game.ghostY();game.matrix.forEach((r,y)=>r.forEach((v,x)=>{if(v){block(ctx,(game.x+x)*30,(gy+y)*30,30,COLORS[game.type],true);block(ctx,(game.x+x)*30,(game.y+y)*30,30,COLORS[game.type])}}))}preview('next',game.queue.slice(0,3));preview('hold',[game.held]);document.querySelectorAll('[data-score]').forEach(e=>e.textContent=game.score.toLocaleString());if(game.score>best){best=game.score;try{localStorage.setItem('cp-tetris-best',String(best))}catch{}}document.querySelectorAll('[data-best]').forEach(e=>e.textContent=best.toLocaleString());$('level').textContent=game.level;$('lines').textContent=game.lines;$('progress').style.width=(game.lines%10)*10+'%'}
function afterLock(lines){fall=grounded=resets=0;if(lines){$('message').textContent=['','SINGLE +','DOUBLE +','TRIPLE +','TETRIS! +'][lines]+[0,100,300,500,800][lines];tone(lines===4?880:660,.18)}else tone(160);if(game.over){running=false;$('overlay').hidden=false;$('title').textContent='Nice run.';$('subtitle').textContent='You scored '+game.score.toLocaleString()+' points and cleared '+game.lines+' lines.';$('start').textContent='Play again →';$('pause').textContent='Pause'}}
function start(){if(paused){togglePause();return}game.reset();running=true;paused=false;fall=grounded=resets=0;last=performance.now();$('overlay').hidden=true;$('message').textContent='Find your flow.';render()}
function togglePause(){if(!running)return;paused=!paused;$('overlay').hidden=!paused;$('title').textContent='Take a breath.';$('subtitle').textContent='Your game is waiting right here.';$('start').textContent='Resume →';$('pause').textContent=paused?'Resume':'Pause';last=performance.now()}
function action(name){if(!running||paused)return;let moved=false;switch(name){case'left':moved=game.move(-1,0);break;case'right':moved=game.move(1,0);break;case'rotate':moved=game.rotate();tone(440);break;case'ccw':moved=game.rotate(-1);break;case'down':if(game.move(0,1)){game.score++;fall=0}break;case'drop':afterLock(game.drop());break;case'hold':if(game.hold()){fall=grounded=resets=0;if(game.over)afterLock(0)}break}if(moved&&grounded>0&&resets<15){grounded=0;resets++}render()}
const mapping={ArrowLeft:'left',ArrowRight:'right',ArrowDown:'down',ArrowUp:'rotate',KeyX:'rotate',KeyZ:'ccw',Space:'drop',KeyC:'hold'};
document.addEventListener('keydown',e=>{if(e.target.tagName==='BUTTON'&&(e.code==='Space'||e.code==='Enter'))return;if(mapping[e.code]){e.preventDefault();if(e.repeat&&['drop','hold','rotate','ccw'].includes(mapping[e.code]))return;action(mapping[e.code])}if(e.code==='KeyP'||e.code==='Escape'){e.preventDefault();if(!e.repeat)togglePause()}if(e.code==='Enter'&&!running)start()});
$('start').onclick=e=>{start();e.currentTarget.blur()};$('pause').onclick=e=>{togglePause();e.currentTarget.blur()};$('sound').onclick=e=>{sound=!sound;e.currentTarget.textContent=sound?'Sound on':'Sound off';e.currentTarget.setAttribute('aria-pressed',String(sound));tone();e.currentTarget.blur()};
document.querySelectorAll('[data-action]').forEach(b=>{let timer,repeat;const stop=()=>{clearTimeout(timer);clearInterval(repeat)};b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);action(b.dataset.action);if(['left','right','down'].includes(b.dataset.action))timer=setTimeout(()=>{repeat=setInterval(()=>action(b.dataset.action),65)},180)});['pointerup','pointercancel','lostpointercapture'].forEach(t=>b.addEventListener(t,stop));b.addEventListener('click',e=>{if(e.detail===0)action(b.dataset.action)})});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused)togglePause()});
function frame(now){let dt=Math.min(now-last,60);last=now;if(running&&!paused){fall+=dt;if(fall>=Math.max(75,850*Math.pow(.8,game.level-1))){game.move(0,1);fall=0}if(!game.valid(game.matrix,game.x,game.y+1)){grounded+=dt;if(grounded>=450)afterLock(game.lock())}else grounded=0;render()}requestAnimationFrame(frame)}render();requestAnimationFrame(frame);
}
